In [6]:
# Solicita ao usuário o nome do arquivo para salvar o conteúdo
nome_arquivo = input("Digite o nome do arquivo para salvar o conteúdo: ")

# Abre o arquivo no modo de escrita
with open(nome_arquivo, 'w') as arquivo:
    while True:
        # Solicita ao usuário o conteúdo a ser armazenado
        conteudo = input("Digite o conteúdo (ou 'sair' para encerrar): ")

        # Verifica se o usuário deseja sair
        if conteudo.lower() == 'sair':
            break

        # Escreve o conteúdo no arquivo
        arquivo.write(conteudo + '\n')

print("Conteúdo foi armazenado no arquivo com sucesso!")


Conteúdo foi armazenado no arquivo com sucesso!


In [3]:
import numpy as np

# Carregamento das matrizes a partir dos arquivos CSV
matriz1 = np.loadtxt('matriz1.csv', delimiter=',')
matriz2 = np.loadtxt('matriz2.csv', delimiter=',')

# Exibindo as matrizes carregadas
print("Matriz 1:")
print(matriz1) # Exibindo a matriz carregada
print("Shape da Matriz 1:", matriz1.shape) # Exibindo as dimensões da matriz

print("\nMatriz 2:") 
print(matriz2) # Exibindo a matriz carregada
print("Shape da Matriz 2:", matriz2.shape) # Exibindo as dimensões da matrizS

# Verificando se as matrizes têm dimensões compatíveis para as operações
if matriz1.shape[1] == matriz2.shape[0]:
    # Realizando a multiplicação de matrizes
    result_dot = np.dot(matriz1, matriz2) 
    print("\nResultado da Multiplicação:")
    print(result_dot) # Exibindo o resultado da multiplicação
    print("Shape do Resultado:", result_dot.shape)
else:
    print("\nAs matrizes não podem ser multiplicadas devido às dimensões incompatíveis.")

# Verificando se as matrizes têm as mesmas dimensões para a soma
if matriz1.shape == matriz2.shape:
    # Realizando a soma de matrizes
    result_sum = np.add(matriz1, matriz2)
    print("\nResultado da Soma:")
    print(result_sum) # Exibindo o resultado da soma
    print("Shape do Resultado:", result_sum.shape)
else:
    print("\nAs matrizes não podem ser somadas devido às dimensões diferentes.")


Matriz 1:
[[1. 2. 3.]
 [4. 5. 6.]]
Shape da Matriz 1: (2, 3)

Matriz 2:
[[ 7.  8.]
 [ 9. 10.]
 [11. 12.]]
Shape da Matriz 2: (3, 2)

Resultado da Multiplicação:
[[ 58.  64.]
 [139. 154.]]
Shape do Resultado: (2, 2)

As matrizes não podem ser somadas devido às dimensões diferentes.


DataFrame é uma ferramenta essencial para a análise exploratória de dados, limpeza, transformação e preparação de dados antes de aplicar algoritmos de aprendizado de máquina ou realizar análises estatísticas.
Alicacoes comuns são:
- Indexação com colunas e linhas
- Seleção de subconjuntos de dados
- Reestruturação de dados usando operações de pivô
- Combinando e mesclando conjuntos de dados
- Transformação de dados usando uma função ou mapeamento
- Filtragem de outliers

In [1]:
import numpy as np

# Criação de uma matriz de valores aleatórios de dimensões 3x3
random_matrix = np.random.randint(0, 100, size=(3, 3))

# Exibindo a matriz gerada
print("Matriz de Valores Aleatórios:")
print(random_matrix)

# Salvando a matriz em um arquivo CSV
np.savetxt('random_matrix.csv', random_matrix, delimiter=',', fmt='%d')

print("\nMatriz salva no arquivo 'random_matrix.csv'.")


Matriz de Valores Aleatórios:
[[39 50 17]
 [56 36 15]
 [58 67 22]]

Matriz salva no arquivo 'random_matrix.csv'.


In [2]:
import numpy as np
import pandas as pd

# Criação de duas matrizes aleatórias de dimensões 3x3
matrix1 = np.random.random((3, 3))
matrix2 = np.random.random((3, 3))

# Exibindo as matrizes geradas
print("Matriz 1:")
print(matrix1)
print("\nMatriz 2:")
print(matrix2)

# Criando DataFrames a partir das matrizes
df_matrix1 = pd.DataFrame(matrix1)
df_matrix2 = pd.DataFrame(matrix2)

# Verificando se as matrizes podem ser multiplicadas
if df_matrix1.shape[1] == df_matrix2.shape[0]:
    # Realizando a multiplicação de DataFrames
    df_result = df_matrix1.dot(df_matrix2)
    print("\nResultado da Multiplicação:")
    print(df_result)
else:
    print("\nAs matrizes não podem ser multiplicadas devido às dimensões incompatíveis.")


Matriz 1:
[[0.49800706 0.43349931 0.55730454]
 [0.25051406 0.05380846 0.25168536]
 [0.72648043 0.32423005 0.20336158]]

Matriz 2:
[[0.7526553  0.17032649 0.86423119]
 [0.40606362 0.94024368 0.27356322]
 [0.14097512 0.34874413 0.91193944]]

Resultado da Multiplicação:
          0         1         2
0  0.629422  0.686775  1.057211
1  0.245882  0.181036  0.460744
2  0.707116  0.499515  0.901998


In [7]:
import pandas as pd

# Parâmetros
chunk_size = 2000  # Tamanho do bloco

# Função para processar cada bloco lido
def process_chunk(chunk):
    # Aqui você pode realizar qualquer processamento desejado no bloco
    # Neste exemplo, estou apenas exibindo o bloco
    print("Bloco lido:")
    print(chunk)
    print("=" * 50)

# Leitura em blocos e processamento
reader = pd.read_csv('ex6.csv', chunksize=chunk_size)
for chunk in reader:
    process_chunk(chunk)


Bloco lido:
           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
1995  2.311896 -0.417070 -1.409599 -0.515821   L
1996 -0.479893 -0.650419  0.745152 -0.646038   J
1997  0.523331  0.787112  0.486066  1.093156   V
1998 -0.362559  0.598894 -1.843201  0.887292   W
1999 -0.096376 -1.012999 -0.657431 -0.573315   D

[2000 rows x 5 columns]
Bloco lido:
           one       two     three      four key
2000  0.467976 -0.038649 -0.295344 -1.824726   1
2001 -0.358893  1.404453  0.704965 -0.200638   H
2002 -0.501840  0.659254 -0.421691 -0.057688   F
2003  0.204886  1.074134  1.388361 -0.982404   L
2004  0.354628 -0.133116  0.283763 -0.837063   E
...        ...       ...       ...       ...  ..
3995  2.311896 -0.41

In [8]:
from collections import Counter

# Função para ler o arquivo e contar as palavras
def count_unique_words(filename):
    unique_word_counter = Counter()  # Usaremos o Counter para contar palavras únicas
    
    with open(filename, 'r') as file:
        for line in file:
            words = line.strip().split()  # Separando palavras da linha
            unique_word_counter.update(words)  # Atualizando o contador com as palavras da linha
    
    return unique_word_counter

# Nome do arquivo
filename = 'ciencia_de_dados.txt'

# Contando palavras únicas
word_counter = count_unique_words(filename)

# Exibindo a contagem de palavras únicas
for word, count in word_counter.items():
    print(f'{word}: {count}')


Ci�ncia: 2
de: 17
dados: 6
(em: 1
ingl�s:: 1
data: 2
science: 1
): 1
�: 3
uma: 1
�rea: 1
interdisciplinar: 1
voltada: 1
para: 3
o: 4
estudo: 1
e: 7
a: 3
an�lise: 2
dados,: 1
estruturados: 1
ou: 2
n�o,: 1
que: 2
visa: 1
extra��o: 1
conhecimento: 1
insights: 2
poss�veis: 1
tomadas: 2
decis�o,: 1
maneira: 1
similar: 1
minera��o: 1
dados.: 1
alia: 1
big: 1
machine: 2
learning,: 1
al�m: 1
t�cnicas: 1
outras: 1
�reas: 2
interdisciplinares: 1
como: 2
estat�stica,: 1
economia,: 1
engenharia: 1
outros: 1
subcampos: 1
da: 1
computa��o: 1
como:: 2
banco: 1
agrupamentos: 1
(cluster: 1
analysis).: 1
A: 2
ci�ncia: 2
um: 1
campo: 1
j�: 1
existe: 1
h�: 1
30: 1
anos,: 1
por�m: 1
ganhou: 1
mais: 1
destaque: 1
nos: 1
�ltimos: 1
anos: 1
devido: 1
alguns: 1
fatores: 1
surgimento: 1
populariza��o: 1
do: 1
Big: 1
Data: 1
desenvolvimento: 1
learning.: 1
pode,: 1
por: 1
exemplo,: 1
transformar: 1
essa: 1
grande: 1
quantidade: 1
brutos: 1
em: 2
neg�cios,: 1
com: 1
isso,: 1
auxiliar: 1
empresas: 1
decis�es: 1
at

O JSON (JavaScript Object Notation) é um formato de troca de dados leve, legível por humanos e independente de linguagem. 
Os dados nele contidos são armazenados em pares de atributo/valor.
aplicacoes comuns são:
- Armazenamento de dados
- Troca de dados entre sistemas
- Formato de dados para APIs
- Arquivos de inicialização
- Configuração de dados