In [2]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[-1.28524365,  0.4559024 , -0.81169751],
       [-0.5029673 ,  0.50773507, -1.63554989]])

In [3]:
res = data * 10
print(res)
res = data + data
print(res)


[[-12.8524365    4.55902404  -8.11697508]
 [ -5.029673     5.07735069 -16.35549893]]
[[-2.5704873   0.91180481 -1.62339502]
 [-1.0059346   1.01547014 -3.27109979]]


In [4]:
print(data.shape)
print(data.dtype)

(2, 3)
float64
