In [6]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [9]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [12]:
print(np.zeros(10))
print(np.zeros((3, 6)))
print(np.empty((3, 6, 2)))
print(np.eye(4, 4))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[9.25839076e-312 9.25836826e-312]
  [0.00000000e+000 0.00000000e+000]
  [2.31297541e-312 1.16097020e-028]
  [1.26087994e-076 2.29673348e-028]
  [8.96902862e-067 1.04917183e-153]
  [5.23081515e-143 1.90353631e+185]]

 [[5.88365473e-062 7.10484500e-038]
  [4.66315783e-033 5.83655227e-144]
  [3.59751658e+252 1.46901661e+179]
  [8.37404147e+242 4.31999013e-096]
  [4.82337723e+228 1.65812186e-076]
  [2.14331426e+184 5.49434123e-090]]

 [[1.56220185e+161 8.16675365e-043]
  [5.04621343e+180 1.94918963e-153]
  [5.04340716e+174 2.32565894e-057]
  [1.53208738e-047 1.43791250e-051]
  [1.04917867e-153 9.08366791e+223]
  [5.82381891e-144 1.03977794e-312]]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])